### ISSUE TITLE
Re-arming the attack heli with a2a missiles

### ISSUE THREAD

**Issue by 3312bKarp** [UncreatedStaff/UncreatedWarfare#12]
Since in the new season in addition to the ground attack jet there will also be a fighter jet i would add a third seat for the gunner of the heli that would be equiped with 2 aa missiles. Attack helis are allready defensless against jets to the point where there is no point of taking off. Having even more jets would make them unusable. 2 missiles would give them at least a fighting chance against jets and would make attack heli on attack heli fights less retarded.

**Comment by UsernameIsUnavailible** [comment]
@3312bKarp 
Season 3 fighter jets will both have A2A missiles, However the attacker jet will only have one seat, So its only use would be to take down enemy aircraft.

We could add in a 3rd seat in the attack heli for A2A missiles but seen in S2, Attack helis & jets work fine the way they are

**Comment by IlosdVay** [comment]
> Since in the new season in addition to the ground attack jet there will also be a fighter jet i would add a third seat for the gunner of the heli that would be equiped with 2 aa missiles. Attack helis are allready defensless against jets to the point where there is no point of taking off. Having even more jets would make them unusable. 2 missiles would give them at least a fighting chance against jets and would make attack heli on attack heli fights less retarded.

Its a helicopter, designed for ground support roles. You need to rely on your team's jet. Adding AA to a heli would make it more powerful in certain situations, and would bring massive balance issues to the game since jets would be useless. Why? Because it can destroy vehicles, soldiers, buildings, and even air assets now! Let's keep the roles clear - Jet for keeping the sky clear and helping infantry to push. Heli to support infantry and destroy ground assets. 

I would add that I always get triple the exp and kills using a heli than a jet...
