### ISSUE TITLE
Suggestion - Mobile mortar vehicles

### ISSUE THREAD

**Issue by UsernameIsUnavailible** [UncreatedStaff/UncreatedWarfare#158]
It'd be cool to see mobile mortar vehicles like the LAV-M & 2S31 Vena. & maybe more sophisticated mortars like adding smoke rounds, HE, HE - Burst & more..

**Comment by DeathFromAbove145** [comment]
I'm unsure of the mobile mortar vehicles, feels like nobody would use it since you would have to re-range everytime you move for accurate shots. The sophisticated mortars idea is good, but it should be carefully implemented. Right now the mortars are balanced, but if they're too messed around with, it could make them a little too op.
