### ISSUE TITLE
Tick speed Issues 

### ISSUE THREAD

**Issue by AngelAbov3** [UncreatedStaff/UncreatedWarfare#161]
Random occurring issue unable to replicate due to not knowing it's cause, here are somethings I have noticed

- Radio burn out is extremely fast about 10xish (ball park guess) the normal speed

- Cap speed is also extremely fast about 10xish (ball park guess) the normal speed

**Comment by benvalkin** [comment]
@AngelAbov3  Is it constantly like this or does it suddenly occur from time to time?

**Comment by AngelAbov3** [comment]
Just suddenly occurs get it about once every 2 days if I had to put a number on it

**Comment by DanielWillett** [comment]
Somehow gamemode event loop is running more often than it should sounds like

**Comment by benvalkin** [comment]
We finally found the bug that was causing this - and it's a silly one that's been around since we added different gamemodes a year ago, caused by bad engineering & communication.

For those interested, when a new game started and happened to be the same gamemode as the previous game, the plugin would 'reload' the gamemode instead of creating a clean new gamemode instance (unlike what would happen if the gamemode was different). It so happened that we (@DanielWillett) forgot to stop the previous game's event tick loop when reloading the gamemode, causing multiple tick loops to run simultaneously. This problem would also worsen every time the same gamemode is picked in a row, although it would finally be fixed when finally a different gamemode was chosen, as the one with multiple tick loops would be destroyed by Unity.

If we had designed the plugin to create clean new gamemodes in all cases instead of adding a slightly different 'reload' feature, this could have easily been avoided.
