### ISSUE TITLE
Remove pilot switching seat (idk i haven't play in awhile)

### ISSUE THREAD

**Issue by Sgtlog123** [UncreatedStaff/UncreatedWarfare#259]
just annoying and unrealistic.

**Comment by Nerfboy-NEO** [comment]
> just annoying and unrealistic.

That is not gonna happen for a reason in particular

It was implemented in so that Heli pilots don't fly over someone on their own, get in the gun seat, and immediately kill someone that's in an emplacement or any infantry in general.

it was the most annoying shit when it was the case, and to combat that, while in the air you cant switch seats

with that being said, 

COPE, SEETHE, AND MALD
