### ISSUE TITLE
Anti Air Improvements

### ISSUE THREAD

**Issue by DMJaxun** [UncreatedStaff/UncreatedWarfare#76]
Been discussed to death but to be more fair and discourage certain behaviours:

- Minimum Distance to lock onto an aircraft (Cant lock targets closer than 100m away)
- Maximum Distance to lock onto an aircraft (Cant lock targets further than 500m away)
- Guidance Failure (Chance for the missile to lose lock over distance logic)

**Comment by UsernameIsUnavailible** [comment]
Let's not get this suggestion flooded, time to react so the Discord sees it :trollface:

**Comment by benvalkin** [comment]
I think the best solution for next season is a vertical cylinder lock-on range which extends really high vertically but with a radius of only 300-400m. I do not want to implement a minimum lock-on range because it messes with how jets acquire targets during close dogfights.

**Comment by benvalkin** [comment]
Also, to make flares more strategic, we could make them very effective and spammable, but finite and reloadable when you do /ammo at main. After you use up all flares, a toast would appear saying "NO FLARES" when you press '/'.

**Comment by benvalkin** [comment]
This has been fixed for S3 with a full rewrite of flares:

- flares look way better and wont get catapulted forward
- flares will be finite but with not cooldown (rearm in main)
- lock on overhaul: heatseakers will play the lock on sound as soon as you look at a heat signature, instead of after you click to shoot (shooting the missile will be instant)
- flares and ground vehicles will be seen from much further away
- much more reliable locking for jet AA - before locks would often be ignored if the target was too close
- better lock on logic overall
- ground AA range will have a horizontal and vertical component to make it less broken

**Comment by DeathFromAbove145** [comment]
Lock on overhaul: does it mean that it plays the lock on sound if you look at an enemy jet with aa, even if you haven't shot yet? I'm just a little confused about it, and if that's the case, wouldn't it mess up the timing of the pilots flaring

**Comment by UsernameIsUnavailible** [comment]
Flares are changed though, You get X charges which you can use without cooldown. & have to re-arm at main.
