### ISSUE TITLE
New items perhaps

### ISSUE THREAD

**Issue by ToastyTimeZ** [UncreatedStaff/UncreatedWarfare#95]
I feel like we've been using a lot of the same guns and equipment (other than vehicles sort of) and so I was wondering if it would be possible to add new things, like perhaps adding another modern HAT weapon like the Panzerfaust or a sniper like the SSG69 that was at 1 point meant to be in the game. I understand if it is pointless do to these things if they might have just copy and pasted stats.

**Comment by HamzaXSniper** [comment]
dude just suggested a new season

**Comment by ToastyTimeZ** [comment]
> dude just suggested a new season

It can always be added in at anytime even if it means in another season, could always even just reuse the RPG-28 possibly

**Comment by HamzaXSniper** [comment]
just make suggestions for next season as much probably wont be implemented this season.

**Comment by DanielWillett** [comment]
Yeah, we do refreshes of equipment and change up the teams and map about every 6 months. Most of the time halfway through the season we also have a smaller content update. This thread is mostly for season 3 stuff as it's a bit of a pain to update older stuff because exporting mods without new content and stuff is not that easy.
