### ISSUE TITLE
Night vision for crewmates

### ISSUE THREAD

**Issue by Pepenas** [UncreatedStaff/UncreatedWarfare#99]
Give crewmates night vision glasses or implemented in their helmet if that's possible

**Comment by Nightshadow935** [comment]
not a bad idea in my opinion. perhaps though maybe not for crew kits. a possibility would be to add them to high tier kits, such as squad lead 3, or similar. if you are really after NVG's in crewmate kits though, I would think that instead of being added to the helmet, they are added to the vehicle. T-90/Abrams main cannon gunner has access to NVG's, similar to how irl tanks of these kinds often have NVG or even infra-red sights for the gunner

**Comment by hat69420** [comment]
its good ngl but shouldnt t90 or abrams have nvg already installed also they should add statiky effects cuz it makes me go yes

**Comment by benvalkin** [comment]
We can't do static night night vision effects that are only active in the vehicle seat and I don't really want to give crewmen night vision, plus the whole idea is a bit extra imo
